@ECHO ON
SET LOCAL=%~dp0\..\Windows\

SET INCLUDE=%INCLUDE%;%LOCAL%\include
SET LIB=%LIB%;%LOCAL%\lib

SET C_INCLUDE_PATH=%C_INCLUDE_PATH%;%LOCAL%\include
SET CPLUS_INCLUDE_PATH=%CPLUS_INCLUDE_PATH%;%LOCAL%\include
SET LIBRARY_PATH=%LIBRARY_PATH%;%LOCAL%\lib

SET PATH=%PATH%;%LOCAL%\bin

make %*

PAUSE